# Generated by Django 2.2.4 on 2019-09-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeresource',
            name='resource_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
