# Generated by Django 2.2.4 on 2019-09-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0003_measurement_measurement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeresource',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compute.Network'),
            preserve_default=False,
        ),
    ]
