# Generated by Django 2.2.4 on 2019-09-09 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compute', '0004_auto_20190902_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computeresource',
            name='owner',
        ),
        migrations.CreateModel(
            name='NetworkOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compute.Network')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
