# Generated by Django 2.2.4 on 2019-09-09 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compute', '0005_auto_20190908_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NetworkOwner',
        ),
    ]
